//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSborkeAdmistrator.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputerCase()
        {
            this.FormFactorMotherboard = new HashSet<FormFactorMotherboard>();
            this.Material = new HashSet<Material>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public int FormFactorId { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public decimal Length { get; set; }
        public decimal Weight { get; set; }
        public decimal MetalWeight { get; set; }
        public Nullable<bool> GlassOnFrontPanel { get; set; }
        public Nullable<int> GlassOnFrontPanelMaterialId { get; set; }
        public Nullable<bool> WindowOnSide { get; set; }
        public Nullable<int> WindowMaterialId { get; set; }
        public int AlignmentPowerBlockId { get; set; }
        public Nullable<int> HorizontalAddonsSlots { get; set; }
        public Nullable<int> VerticalAddonsSlots { get; set; }
        public int MaxLengthVideocard { get; set; }
        public int MaxHeightCPUCooler { get; set; }
        public Nullable<int> CountSlotSDD { get; set; }
        public Nullable<int> CountSlotHDD { get; set; }
        public Nullable<bool> CoolerAdd { get; set; }
        public Nullable<int> CoolerInside { get; set; }
        public Nullable<int> CoolerSizeId { get; set; }
        public Nullable<bool> SupportFrontCooler { get; set; }
        public Nullable<bool> SupportBackCooler { get; set; }
        public Nullable<bool> SupportTopCooler { get; set; }
        public Nullable<bool> SupportSideCooler { get; set; }
        public Nullable<bool> SupportBottomCooler { get; set; }
        public Nullable<bool> SupportLiquidCooling { get; set; }
        public Nullable<int> LiquidCoolingSizeId { get; set; }
        public int OrientationMotherboardId { get; set; }
        public Nullable<bool> DustFilter { get; set; }
        public int PrimaryColorId { get; set; }
        public Nullable<int> SecondColorId { get; set; }
        public int IOPanelId { get; set; }
        public Nullable<bool> CableManagement { get; set; }
        public Nullable<bool> CardReader { get; set; }
        public int SidePanalFixationId { get; set; }
        public Nullable<bool> RGB { get; set; }
        public Nullable<int> TypeRGBId { get; set; }
        public Nullable<int> ColorRGBId { get; set; }
        public Nullable<bool> HubRGB { get; set; }
        public byte[] MainImage { get; set; }
        public Nullable<int> ComputerCaseImagesId { get; set; }
        public int ManufacturerId { get; set; }
        public string DeliverySet { get; set; }
        public Nullable<bool> SpecialDesign { get; set; }
        public Nullable<bool> IsAccessable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CommentAccessable { get; set; }
        public Nullable<bool> IsCustom { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual AlignmentPowerBlock AlignmentPowerBlock { get; set; }
        public virtual ColorId ColorId { get; set; }
        public virtual ColorId ColorId1 { get; set; }
        public virtual ColorRGB ColorRGB { get; set; }
        public virtual ComputerCaseImages ComputerCaseImages { get; set; }
        public virtual CoolerSize CoolerSize { get; set; }
        public virtual FormFactor FormFactor { get; set; }
        public virtual IOPanel IOPanel { get; set; }
        public virtual LiquidCoolingSize LiquidCoolingSize { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual OrientationMotherboard OrientationMotherboard { get; set; }
        public virtual SidePanelFixation SidePanelFixation { get; set; }
        public virtual TypeRGB TypeRGB { get; set; }
        public virtual User User { get; set; }
        public virtual WindowMaterial WindowMaterial { get; set; }
        public virtual WindowMaterial WindowMaterial1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormFactorMotherboard> FormFactorMotherboard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
    }
}
