//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSborkeAdmistrator.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerCaseImages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputerCaseImages()
        {
            this.ComputerCase = new HashSet<ComputerCase>();
        }
    
        public int Id { get; set; }
        public byte[] FrontImage { get; set; }
        public byte[] BackImage { get; set; }
        public byte[] TopImage { get; set; }
        public byte[] BottomImage { get; set; }
        public byte[] PlanImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerCase> ComputerCase { get; set; }
    }
}
