//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSborkeAdmistrator.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverManOrder
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateStart { get; set; }
        public int DeliveryStatusId { get; set; }
    
        public virtual DeliveryStatus DeliveryStatus { get; set; }
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
