//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSborkeMaster.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VSborkeBaseEntities : DbContext
    {
        public VSborkeBaseEntities()
            : base("name=VSborkeBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionComputerCaseImage> AdditionComputerCaseImage { get; set; }
        public virtual DbSet<AlignmentPowerBlock> AlignmentPowerBlock { get; set; }
        public virtual DbSet<BackLiquidCooling> BackLiquidCooling { get; set; }
        public virtual DbSet<BottomLiquidCooling> BottomLiquidCooling { get; set; }
        public virtual DbSet<ColorRGB> ColorRGB { get; set; }
        public virtual DbSet<ComputerCase> ComputerCase { get; set; }
        public virtual DbSet<ConnectorRGB> ConnectorRGB { get; set; }
        public virtual DbSet<CoolerInside> CoolerInside { get; set; }
        public virtual DbSet<Favourite> Favourite { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<FormFactor> FormFactor { get; set; }
        public virtual DbSet<FrontLiquidCooling> FrontLiquidCooling { get; set; }
        public virtual DbSet<FrontPanelMaterial> FrontPanelMaterial { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<HorizontalAddonSlot> HorizontalAddonSlot { get; set; }
        public virtual DbSet<IOPanel> IOPanel { get; set; }
        public virtual DbSet<IOPanelAlignment> IOPanelAlignment { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<MaterialSet> MaterialSet { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrientationMotherboard> OrientationMotherboard { get; set; }
        public virtual DbSet<PowerBlockStandartSupport> PowerBlockStandartSupport { get; set; }
        public virtual DbSet<PriceHistory> PriceHistory { get; set; }
        public virtual DbSet<PrimaryColor> PrimaryColor { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SecondColor> SecondColor { get; set; }
        public virtual DbSet<SideLiquidCooling> SideLiquidCooling { get; set; }
        public virtual DbSet<SidePanelFixation> SidePanelFixation { get; set; }
        public virtual DbSet<SlotHDD> SlotHDD { get; set; }
        public virtual DbSet<SlotSSD> SlotSSD { get; set; }
        public virtual DbSet<SlotXHDD> SlotXHDD { get; set; }
        public virtual DbSet<SourceRGB> SourceRGB { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SupportBackCooler> SupportBackCooler { get; set; }
        public virtual DbSet<SupportBottomCooler> SupportBottomCooler { get; set; }
        public virtual DbSet<SupportFrontCooler> SupportFrontCooler { get; set; }
        public virtual DbSet<SupportSideCooler> SupportSideCooler { get; set; }
        public virtual DbSet<SupportTopCooler> SupportTopCooler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TopLiquidCooling> TopLiquidCooling { get; set; }
        public virtual DbSet<TypeManagmentRGB> TypeManagmentRGB { get; set; }
        public virtual DbSet<TypeRGB> TypeRGB { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VerticalAddonSlot> VerticalAddonSlot { get; set; }
        public virtual DbSet<WindowAlignment> WindowAlignment { get; set; }
        public virtual DbSet<WindowMaterial> WindowMaterial { get; set; }
    }
}
